### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Goldinium** [Goldinium/Space_Travelers_Hub#21]
Hello,

There are two developers working on this project

@ometman  & @Goldinium 

https://github.com/users/Goldinium/projects/2

Thank you!

**Comment by DammyShittu** [comment]
Hi @Goldinium and @ometman,

## Highlights
✔️ Descriptive issue

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly use the template as guideline. See the image below. We don't have a "No Status" column. Kindly remove it. We should only have To do, In Progress, In review and Done columns. Kindly add the In Review column and remove the No Status column

- [ ] Since there are only two team members, kindly remove the [Team 3] tasks. From the image you can see a Team 3 task.

- [ ] The number of tasks you have should be 17 after removing all Team 3. Kindly ensure you are thorough when creating your tasks that template.

- [ ] Kindly ensure all tasks are assigned, including the group tasks.

  ![image](https://github.com/Goldinium/Space_Travelers_Hub/assets/54848363/ef97215a-f739-4f99-9afc-26d8ce0f967e)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Goldinium** [comment]
Done changes

**Comment by julie-ify** [comment]
Hi @Goldinium and @ometman,

## Highlights!
- Descriptive issue ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
